### ISSUE TITLE
Enable support for Android TV

### ISSUE THREAD

**Issue by badaix** [badaix/snapdroid#3]
_From @voltagex on April 28, 2018 6:33_

![image](https://user-images.githubusercontent.com/159567/39392909-cdeaf7f0-4b01-11e8-846b-1963b38f0551.png)

Could you please enable Android TV support in the Store version of the app? I'll probably recompile it for my TV but it'd be nice to be able to just install it.

_Copied from original issue: badaix/snapcast#392_

**Comment by badaix** [comment]
please move this issue to [snapdroid](https://github.com/badaix/snapdroid/issues)

**Comment by voltagex** [comment]
Oops, thanks for moving this.

**Comment by sirl1on** [comment]
Works with sideloaded APK on Nvidia shield TV!

**Comment by cyberbix** [comment]
Works well on FireTV, sideloaded via adblink. Had to give an extra delay of 100ms on my Philips TV.

**Comment by ghzgod** [comment]
Doesn't work on Sony TV after sideloading via ADB

**Comment by foxy82** [comment]
This doesn't seem to work for playing audio when side loaded on to a Google TV dongle (https://store.google.com/gb/product/chromecast_google_tv?hl=en-GB) however I can see the list of clients.

When I hit play I get a constantly appearing/disappearing/reappearing message at the bottom of the screen that reads:
"Error in socket shutdown: Transport endpoint is not connected"

**Comment by toffee** [comment]
On my Philips TV (model PUS8505/12) with Android 9 installing snapcast (version 0.26.0.0) via sideloading is possible and is working. To access the Snapcast application you need to install from Google play a "Sideload Launcher" app. 

Anyway, there are some caveats:
 * the navigation with remote control in the application is difficult (wasn't able to mute/unmute, set source, etc for displayed clients); No critical for me because I can use the snapcast web for this.  
 * accessing the start/stop and three dots button is counter intuitive - need to press 2x fast (at first press the tooltip is displayed); Again, there is a workaround - no problem for me.
 * when the TV is put to stand-by (not power off, the server does not see this client as disconnected - no "onDisconnect: xxxxx-xxx" messages on snapserver log) the sound is stopped (normally, the TV is off) but when switch on the TV the client is displayed as started, unmuted but no sound is heard. You need to stop/start the client in order to get sound again. For me this is annoying and I would like to see this issue fixed.

**Comment by XeOS1977** [comment]
First of.... a massive thanks for your work, entire house was running on snapcast a while back without a hitch in combination with Home Assistant. Unfortunately after the update of my Nvidia Shield to Android 11 the (Snapdroid) snapcast client became unavailable as an output source. The app is working and I can control other instances but no more sound on the surround system. Also purchased a new TV recently with Android TV (Android 11) as well. Same issue.
It would be awesome if we could use snapcast clients again on Android/Google TV again

**Comment by chatziko** [comment]
WIth some minor troubles, I managed to make the snapcast client work on a Chromecast with Google TV. Here's how for anyone who's interested.

I first sideloaded the apk (found in the [releases](https://github.com/badaix/snapdroid/releases/tag/v0.26.0) page):
```
adb connect <chromecast-IP>
adb install Snapcast_0.26.0.apk
```

The only problem after the installation is that the app won't show anywhere, not even in the full list of installed apps. But it is nevertheless installed, and can be launched with:
```
adb shell monkey -p de.badaix.snapcast -c android.intent.category.LAUNCHER 1
```

After this, everything works as expected, the app detects the server, and we just have to press the `Play` button (a bit tricky with the remote, we first need to focus the button, but it's doable). Then Chromecast appears in the list of snapcat clients and plays audio (even simultaneously with other apps).

Finally, we can select `three dots / Settings / Auto start Snapclient`. This way snapclient loads automatically on boot, and we never have to interact with the UI again (we can control the sound from any snapcast controller).

PS1. Of course, some proper support for Android TV would be hugely welcome. Since the main functionality is working, I guess it shouldn't be too hard.

PS2. Thanks for this awesome project!

**Comment by jagjordi** [comment]
I am also running snapdroid sideloaded on android TV. However I notice that when snapcast is playing the screensaver wont start. Have any of you noticed that? And any ideas on how to solve it?

**Comment by jagjordi** [comment]
My workarround as of now is to trigger screensaver through home assistant with an automation: 

```
service: androidtv.adb_command
data:
  command: adb shell am start -n "com.android.systemui/.Somnambulator"
target:
  entity_id: media_player.android_tv
```

**Comment by SantiagoSotoC** [comment]
I have the project modified so it can be launched from android tv, I have to fix the banner and make it a pull request, most likely for tomorrow.
I know little about android development, we can go see the problems little by little.

**Comment by pmec** [comment]
I made a [PR](https://github.com/badaix/snapdroid/pull/67) to solve this.

**Comment by XeOS1977** [comment]
Thanks @SantiagoSotoC and @pmec for the modifications, it shows up in my apps. Way easier than having to try and start it from settings->apps etc. 
I still have the problem though that it doesn't show as a player/client and therefore doesn't give sound. This happens on a Nvidia Shield tube 2019. It stopped working ever since the upgrade to Android 11, same goes for my Android TV (also version 11). Please advice on how to debug this or is this is known?

**Comment by ndesgranges** [comment]
> My workarround as of now is to trigger screensaver through home assistant with an automation:
> 
> ```
> service: androidtv.adb_command
> data:
>   command: adb shell am start -n "com.android.systemui/.Somnambulator"
> target:
>   entity_id: media_player.android_tv
> ```
@jagjordi Is your solution working properly for you ? I'm having the same issue (posted about it here #78), but I don't see how you know when to trigger this. How do you know when the TV is inactive for some time and not playing medias ?

**Comment by jagjordi** [comment]
```
alias: TV - Living room - Start screensaver
description: ""
mode: single
triggers:
  - entity_id:
      - media_player.android_tv
    to: standby
    for:
      hours: 0
      minutes: 5
      seconds: 0
    trigger: state
  - entity_id:
      - media_player.android_tv
    to: paused
    for:
      hours: 0
      minutes: 5
      seconds: 0
    trigger: state
conditions:
  - condition: not
    conditions:
      - condition: state
        entity_id: media_player.living_room_tv
        state: "off"
  - condition: not
    conditions:
      - condition: state
        entity_id: media_player.android_tv
        attribute: source
        state: Jellyfin
  - condition: not
    conditions:
      - condition: state
        entity_id: media_player.android_tv
        attribute: source
        state: IPTV Smarters Pro
actions:
  - data:
      command: adb shell am start -n "com.android.systemui/.Somnambulator"
    target:
      entity_id: media_player.android_tv
    action: androidtv.adb_command
```
This is the full automation. It is not perfect sometimes it triggers accidentally but it works reasonably well

Another solution I have tried is to kill the snapcast client using adb after some time of inactivity.
```
adb shell am force-stop de.badaix.snapcast
```
Then re-start it after music starts to play.
```
adb shell am start -n de.badaix.snapcast/de.badaix.snapcast.MainActivity
```
The anoying part with this is that it sometimes does not auto-start playing
